### ISSUE TITLE
EC2 has a Illegal Access for the Log4J Files

### ISSUE THREAD

**Issue by jdpressley5** [revaturelabs/trackforce#806]
Running the trackforce locally does not update log files in the /target folder. This is most likely due to a configuration issue. Cache messages are not being logged here.

**Comment by jdpressley5** [comment]
Currently disabled in "Caching and Logging" pull request. The properties file is located in that pull request has a variety of options to help format the log output once the issue is resolved. Best of luck to next iteration.

**Comment by davidcheng1760** [comment]
This is what is printed in the EC2:
29-Oct-2018 13:49:20.279 INFO [C3P0PooledConnectionPoolManager[identityToken->1br9z5i9y17iyndtayz3xi|2647d9c7]-HelperThread-#2] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.mchange.v2.resourcepool.BasicResourcePool]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.mchange.v2.resourcepool.BasicResourcePool]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1329)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1317)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1176)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.loadClass(PackagingDataCalculator.java:202)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.bestEffortLoadClass(PackagingDataCalculator.java:221)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.computeBySTEP(PackagingDataCalculator.java:136)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.populateUncommonFrames(PackagingDataCalculator.java:111)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.populateFrames(PackagingDataCalculator.java:103)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.calculate(PackagingDataCalculator.java:55)
        at ch.qos.logback.classic.spi.ThrowableProxy.calculatePackagingData(ThrowableProxy.java:147)
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:129)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:439)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:395)
        at ch.qos.logback.classic.Logger.debug(Logger.java:518)
        at com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$DebugLogger.log(Slf4jMLog.java:207)
        at com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger.log(Slf4jMLog.java:256)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1958)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

29-Oct-2018 13:49:20.280 INFO [C3P0PooledConnectionPoolManager[identityToken->1br9z5i9y17iyndtayz3xi|2647d9c7]-HelperThread-#2] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1329)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1317)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1176)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.loadClass(PackagingDataCalculator.java:202)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.bestEffortLoadClass(PackagingDataCalculator.java:221)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.computeBySTEP(PackagingDataCalculator.java:136)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.populateUncommonFrames(PackagingDataCalculator.java:111)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.populateFrames(PackagingDataCalculator.java:103)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.calculate(PackagingDataCalculator.java:55)
        at ch.qos.logback.classic.spi.ThrowableProxy.calculatePackagingData(ThrowableProxy.java:147)
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:129)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:439)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:395)
        at ch.qos.logback.classic.Logger.debug(Logger.java:518)
        at com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$DebugLogger.log(Slf4jMLog.java:207)
        at com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger.log(Slf4jMLog.java:256)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1958)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

[DEBUG] An exception occurred while acquiring a poolable resource. Will retry.
java.util.MissingResourceException: Can't find bundle for base name oracle.net.jdbc.nl.mesg.NLSR, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573) ~[na:1.8.0_161]
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396) ~[na:1.8.0_161]
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854) ~[na:1.8.0_161]
        at oracle.net.jdbc.nl.NetStrings.<init>(NetStrings.java:52) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.net.jdbc.nl.NLException.initErrorMessage(NLException.java:74) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.net.jdbc.nl.NLException.<init>(NLException.java:52) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.net.jdbc.nl.NVTokens.popLiteral(NVTokens.java:398) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.net.jdbc.nl.NVFactory.getContext(NVFactory.java:241) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.net.jdbc.nl.NVFactory._readTopLevelNVPair(NVFactory.java:92) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.net.jdbc.nl.NVFactory.createNVPair(NVFactory.java:61) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.jdbc.driver.PhysicalConnection.isDRCPConnection(PhysicalConnection.java:9240) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:681) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870) ~[c3p0-0.9.5.2.jar:0.9.5.2]
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696) [mchange-commons-java-0.2.11.jar:0.2.11]
